/* Generated by Together */

package com.hp.hpl.sparta.xpath;

/** A '@attrName' test to see if attribute exists. 

 <blockquote><small> Copyright (C) 2002 Hewlett-Packard Company.
 This file is part of Sparta, an XML Parser, DOM, and XPath library.
 This library is free software; you can redistribute it and/or
 modify it under the terms of the <a href="doc-files/LGPL.txt">GNU
 Lesser General Public License</a> as published by the Free Software
 Foundation; either version 2.1 of the License, or (at your option)
 any later version.  This library is distributed in the hope that it
 will be useful, but WITHOUT ANY WARRANTY; without even the implied
 warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 PURPOSE. </small></blockquote>
 @version  $Date: 2002/12/13 18:08:32 $  $Revision: 1.3 $
 @author Eamonn O'Brien-Strain
 */
public class AttrExistsExpr extends AttrExpr {

  AttrExistsExpr(String attrName) {
    super(attrName);
  }

  public void accept(BooleanExprVisitor visitor) throws XPathException {
    visitor.visit(this);
  }

  public String toString() {
    return "[" + super.toString() + "]";
  }
}

// $Log: AttrExistsExpr.java,v $
// Revision 1.3  2002/12/13 18:08:32  eobrain
// Factor Visitor out into separate visitors for node tests and predicates.
//
// Revision 1.2  2002/12/06 23:41:49  eobrain
// Add toString() which returns the original XPath.
//
// Revision 1.1.1.1  2002/08/19 05:04:05  eobrain
// import from HP Labs internal CVS
//
// Revision 1.2  2002/08/18 23:38:08  eob
// Add copyright and other formatting and commenting in preparation for
// release to SourceForge.
//
// Revision 1.1  2002/02/01 02:07:46  eob
// initial
